### ISSUE TITLE
[Feature] Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [rupali-codes/LinksHub#1295]
### Description

**Issue:** Files like website **pages/index.tsx**, **pages/search.tsx**, **pages/[subcategory]/index.tsx** does not have important meta tags.

**Impact:** This means that the website is not as visible in search results, and users are less likely to click on the website's links.

**Resolution:** The website should contain important meta tags. This will help the website rank higher in search results and attract more visitors.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by rupali-codes** [comment]
@Avinash905 thanks, you may start working on this issue :)
