### ISSUE TITLE
[ADD] Introduction to Frontend by META

### ISSUE THREAD

**Issue by Ram-tyagi** [rupali-codes/LinksHub#2068]
### Category Name

Frontend

### Subcategory Name

React

### Additional Context

@anm

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023
