### ISSUE TITLE
[Feature] Add meta tags for SEO and Social Media Optimization

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#976]
### Description

Several meta tags seem to be missing, and I would like to add these meta tags in the `_document.js` file.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal You are willing to work on every issue you make 😄😄, let's open the opportunities for others :)

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal You are willing to work on every issue you make 😄😄, let's open the opportunities for others :)

Yes, I will contribute every issue myself. Since it takes time to analyze the missing code, I request you to let me contribute to every issue that I make. I have made contributions to gain your trust, so please don't assign it to anyone else.

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal You are willing to work on every issue you make 😄😄, let's open the opportunities for others :)
> 
> Yes, I will contribute every issue myself. Since it takes time to analyze the missing code, I request you to let me contribute to every issue that I make. I have made contributions to gain your trust, so please don't assign it to anyone else.

Okay, :))
